"""MCP tools for firing any Studio Pro command or macro by name.

Resolves a function name against the per-user command catalog generated by
``studio_one_mcp.keyscheme`` from the user's exported ``.keyscheme`` file (see
``studio_one_generate_command_catalog`` in ``tools/keyscheme_tools.py``), and
dispatches it through the DAW's Ctrl+K command palette
(``studio_one_mcp.keystrokes.run_via_command_palette``). Covers every built-in
command and every installed macro — no MIDI involved.
"""

from __future__ import annotations

import logging
from typing import Any

from mcp.types import TextContent, Tool

from studio_one_mcp.keyscheme import load_catalog
from studio_one_mcp.keystrokes import KeystrokeError, run_via_command_palette

log = logging.getLogger(__name__)

CatalogEntry = dict[str, Any]
CatalogMatch = tuple[str, CatalogEntry]


def resolve(name: str, catalog: dict[str, CatalogEntry]) -> CatalogMatch | list[CatalogMatch] | None:
    """Return the matching catalog entry, a list of candidates if ambiguous, or None."""
    n = name.strip().lower()
    entries = list(catalog.items())
    for key, entry in entries:  # exact label match
        if entry["label"].lower() == n:
            return key, entry
    subs = [(key, entry) for key, entry in entries if n in entry["label"].lower()]
    if len(subs) == 1:
        return subs[0]
    return subs or None


def _command_tools() -> list[Tool]:
    return [
        Tool(
            name="studio_one_run_command",
            description=(
                "Run any Studio Pro command or macro by name — e.g. 'Duplicate', "
                "'Split Range', 'Quantize', 'Add EQ'. Covers every built-in command "
                "and every macro installed on this machine. Case-insensitive; a "
                "unique partial match is accepted. Use studio_one_list_commands to "
                "discover names, or studio_one_generate_command_catalog if the list "
                "looks stale."
            ),
            input_schema={
                "type": "object",
                "properties": {"name": {"type": "string", "description": "Command or macro name"}},
                "required": ["name"],
            },
        ),
        Tool(
            name="studio_one_list_commands",
            description=(
                "List available Studio Pro commands and macros, optionally filtered "
                "by a search term."
            ),
            input_schema={
                "type": "object",
                "properties": {"filter": {"type": "string", "description": "Substring filter"}},
                "required": [],
            },
        ),
        Tool(
            name="studio_one_save_new_version",
            description=(
                "Save a new version of the current song before starting a complex or "
                "multi-step change, so the current state is preserved and can be "
                "restored if something goes wrong. Call this before risky work, not "
                "before every single command."
            ),
            input_schema={"type": "object", "properties": {}, "required": []},
        ),
    ]


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------


async def _dispatch(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    catalog = load_catalog()
    if not catalog:
        return [
            TextContent(
                type="text",
                text=(
                    "ERROR: no command catalog found. Run studio_one_generate_command_catalog "
                    "first."
                ),
            )
        ]

    if name == "studio_one_list_commands":
        flt = (arguments.get("filter") or "").strip().lower()
        items = sorted({e["label"] for e in catalog.values() if flt in e["label"].lower()})
        body = "\n".join(f"- {x}" for x in items) if items else "(no matches)"
        return [TextContent(type="text", text=f"{len(items)} command(s):\n{body}")]

    if name == "studio_one_save_new_version":
        return await _run_named(catalog, "Save New Version...", confirm_dialog=True)

    # studio_one_run_command
    fname = arguments.get("name", "")
    return await _run_named(catalog, fname)


async def _run_named(
    catalog: dict[str, CatalogEntry], query: str, *, confirm_dialog: bool = False
) -> list[TextContent]:
    match = resolve(query, catalog)
    if match is None:
        return [TextContent(type="text", text=f"ERROR: no command matching {query!r}")]
    if isinstance(match, list):
        cands = ", ".join(entry["label"] for _key, entry in match[:10])
        return [TextContent(type="text", text=f"Ambiguous {query!r}. Candidates: {cands}")]
    key, entry = match
    category = key.split("|", 1)[0]
    try:
        await run_via_command_palette(entry["label"], confirm_dialog=confirm_dialog)
    except KeystrokeError as exc:
        return [TextContent(type="text", text=f"ERROR: {exc}")]
    return [TextContent(type="text", text=f"Ran '{entry['label']}' [{category}]")]
